---
- name: Prepare timestamp
  hosts:
    - localhost
  connection: local
  gather_facts: yes

  vars:
    systime: "{{ ansible_date_time.time | replace(':', '-') }}"

  tasks:
    - debug: var=ansible_date_time.time
    - debug: var=systime

    - name: get system date and time
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ systime }}"

- name: Backup Device Configuration
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    backup_dir: "{{ user_data_path }}/config_backups/{{ inventory_hostname }}"
    temp_conf_file: "{{ backup_dir}}/{{ inventory_hostname }}"
    conf_file: "{{ temp_conf_file }}_{{ hostvars.localhost.timestamp }}.conf"
    commit_file: "{{ backup_dir }}/{{ inventory_hostname }}_{{ hostvars.localhost.timestamp }}.commit"

  tasks:
    - name: create backup directory if needed
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: save device configuration in temporary file
      junos_get_config:
        host: "{{ ansible_host }}"
        dest: "{{ temp_conf_file }}"
        format: text
      register: config_results

    - debug: var=config_results

    - name: copy temporary file to timestamped config file if different
      copy:
        src: "{{ temp_conf_file }}"
        dest: "{{ conf_file }}"
      when: config_results.changed

    - name: save commit history
      commit_history:
        host: "{{ ansible_host }}"
        filename: "{{ commit_file }}"
        max_commits: 2
      when: config_results.changed
      register: commit_history

    - name: print author of last commit
      debug:
        var: commit_history.commits[0]['user']
      when: commit_history is defined
