---
- name: Prepare temp backup directory
  hosts:
    - localhost
  connection: local
  gather_facts: no

  tasks:
    - name: fail if filter not defined
      fail:
        msg: >
          Specify the Junos configuration hierarchy you want to back up by
          providing the extra variable 'filter' on the command line.
          For example, --extra-vars 'filter=system/ntp'
      when: filter is not defined

    - set_fact: tmp_dir=tmp

    - name: erase (old) backup directory (if it exists)
      file:
        path: "{{ tmp_dir }}"
        state: absent

    - name: create backup directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: show filter setting from command line
      debug:
        var: filter
        verbosity: 1

- name: Get partial device configurations
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: retrieve configuration and save to file
      junos_get_config:
        host: "{{ ansible_host }}"
        dest: "{{ hostvars.localhost.tmp_dir }}/{{ inventory_hostname }}.conf"
        format: "text"
        filter: "{{ filter }}"
        options: {'database':'committed','groups':'groups','inherit':'inherit'}
