---
- name: Get configuration history
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get commit history
      commit_history:
        host: "{{ ansible_host }}"
        max_commits: 3
        filename: "{{ inventory_hostname}}-commit-history.txt"
      register: history

    - debug: var=history.commits
