---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: save device information using template
      template:
        src: template/base-settings-1.1.j2
        dest: "{{ conf_file }}"

    - name: install generated configuration file onto device
      junos_install_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        passwd: "{{ password }}"
        port: 22
        file: "{{ conf_file }}"
        timeout: 120
        replace: yes
        comment: "playbook base-settings.yaml"
