---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"
    netmask: "24"
    username: root
    terminal_server: 198.51.100.100
    term_serv_port: 7001

  # vars_prompt:
  #   - name: username
  #     prompt: Junos Username
  #     private: no
  #
  #   - name: password
  #     prompt: Junos Password
  #     private: yes

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: save device information using template
      template:
        src: template/initial-ex-vlan.j2
        dest: "{{ conf_file }}"

    - name: install generated configuration file onto device
      junos_install_config:
        host: "{{ terminal_server }}"
        file: "{{ conf_file }}"
        user: "{{ username }}"
        # passwd: "{{ password }}"
        timeout: 120
        overwrite: yes
        mode: telnet
        port: "{{ term_serv_port }}"
        comment: "playbook initial-setup-ts.yaml"
