---
- name: Get facts from Junos device
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get device facts
      junos_get_facts:
        host: "{{ ansible_host }}"
      register: junos_facts

    - name: show device facts
      debug:
        var: junos_facts
