---
- name: Set up report directory
  hosts:
    - localhost
  connection: local
  gather_facts: no

  tasks:
    - name: generate report directory name
      set_fact:
        report_dir: "{{ user_data_path }}/reports"

    - name: confirm/create report directory
      file:
        path: "{{ report_dir }}"
        state: directory

- name: Get facts from Junos device
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get device facts
      junos_get_facts:
        host: "{{ ansible_host }}"
      register: junos_facts

    - name: show device facts
      debug:
        var: junos_facts
        verbosity: 1

    - name: save device information using template
      template:
        src: template/device-facts-2f.j2
        dest: "{{ hostvars.localhost.report_dir }}/{{ inventory_hostname }}.txt"
