---
- name: Get device commit history
  hosts:
    - all
  connection: local
  gather_facts: no

  tasks:
    - name: get commit history using ansible core module
      junos_rpc:
        rpc: get-commit-information
        output: xml
        provider:
          host: "{{ ansible_host }}"
      register: history

    - name: display history
      debug: var=history
