---
- name: Get Junos version
  hosts:
    - all
  connection: local
  gather_facts: no

  tasks:
    - name: get junos version using ansible core module
      junos_rpc:
        rpc: get-software-information
        output: text
        provider:
          host: "{{ ansible_host }}"
      register: jversion
      retries: 2
      delay: 15
      until: jversion | success

    - name: display junos version output
      debug: var=jversion
