---
- name: Get LLDP neighbor and save for configuring interface descriptions
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "{{ user_data_path }}/tmp"
    lldp_file_prefix: "{{ tmp_dir}}/{{ inventory_hostname }}-lldp-"

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: get lldp neighbor table
      junos_rpc:
        rpc: get-lldp-interface-neighbors-information
        format: xml
        kwargs:
          interface_name: "{{ item }}"
        host: "{{ ansible_host }}"
        dest: "{{ lldp_file_prefix }}{{ item | replace('/', '-') }}.xml"
      with_items: "{{ aja_host.uplinks }}"
