---
- name: Get Junos version
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get junos version using galaxy module
      junos_rpc:
        rpc: get-software-information
        format: text
        dest: "{{ inventory_hostname }}-version.txt"
        host: "{{ ansible_host }}"
      register: jversion
      retries: 2
      delay: 15
      # until: jversion | success
      until: (jversion | success) or (jversion.msg.find("ConnectAuthError") >= 0)

    - name: display junos_rpc result
      debug: var=jversion
