---
- name: Experiment with Ansible's xml module
  hosts:
    - localhost
  connection: local
  gather_facts: no

  tasks:
    - name: get neighbor details
      xml:
        path: bilbo-lldp.xml
        # xpath: //lldp-neighbor-information[lldp-local-interface='ge-0/0/9.0']
        # xpath: //lldp-neighbor-information[lldp-local-interface='ge-0/0/9.0']/*
        # xpath: //lldp-neighbor-information[lldp-local-interface='ge-0/0/9.0']/lldp-remote-system-name
        # xpath: //lldp-neighbor-information[starts-with(lldp-local-interface, 'ge-0/0/9')]/*
        xpath: //lldp-neighbor-information[starts-with(lldp-local-interface, 'ge-0/1/')]/lldp-remote-system-name
        content: text
      register: neighbors

    - debug: var=neighbors
