---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"

  tasks:
    - name: confirm or create configs directory
      file:
        path: "{{ tmp_dir }}"
        state: directory

    - name: save device information using template
      template:
        src: template/base-settings-2.j2
        dest: "{{ conf_file }}"

    - name: install generated configuration file onto device
      junos_install_config:
        host: "{{ ansible_host }}"
        file: "{{ conf_file }}"
        timeout: 120
        replace: yes
        confirm: 10
        comment: "playbook base-settings-2.yaml, commit confirmed"
      notify: confirm commit

    # - name: delete generated configuration file
    #   file:
    #     path: "{{ conf_file }}"
    #     state: absent

  handlers:
    - name: confirm commit
      junos_commit:
        host: "{{ ansible_host }}"
        timeout: 120
        comment: "playbook base-settings-2.yaml, confirming previous commit"
